In [116]:
import pandas as pd
import numpy as np
import os
from sklearn.impute import SimpleImputer
from sklearn.feature_selection import SelectKBest,mutual_info_regression
from sklearn.model_selection import train_test_split
from sklearn.linear_model import LinearRegression

In [117]:
try:
    from category_encoders import TargetEncoder
except ImportError:
    TargetEncoder=None
    print("waring: category_encoder not installed ")

In [118]:
print("Loading Dataset..")
file_path='train.csv'
if not os.path.exists(file_path):
    print('file not found !')
else:
    df=pd.read_csv(file_path)
    print(f"file found and loaded!\n Rows:{df.shape[0]},Features:{df.shape[1]}")

Loading Dataset..
file found and loaded!
 Rows:581,Features:24

In [119]:
df.head()

,ID,W,G,R,AB,H,1B,2B,3B,HR,...,HBP,BBHBP,SF,Outs,Outsinplay,RA,BA,OBA,SLG,OPS
0,1,60,162,558,5336,1280,891,247,31,111,...,0,460,0,4056,3216,740,0.239880,0.300207,0.360195,0.660402
1,3,86,161,677,5620,1492,1147,216,46,83,...,0,531,0,4128,3376,643,0.265480,0.328890,0.364591,0.693480
2,5,79,162,679,5550,1496,1088,262,63,83,...,0,543,0,4054,3175,710,0.269550,0.334646,0.384324,0.718971
3,7,96,162,780,5536,1458,990,265,40,163,...,0,561,0,4078,3145,682,0.263367,0.331146,0.414017,0.745164
4,9,96,162,688,5441,1354,905,247,21,181,...,55,597,35,4087,2703,548,0.248851,0.321258,0.401764,0.723022

In [120]:
df.loc[0:25,'H']=np.nan   #creating the null values
print(df.head())
imputer=SimpleImputer(strategy='most_frequent')   #imputing means filling the null values
df['H'] = imputer.fit_transform(df[['H']])
print(df.isnull().sum())
print(df.head())

   ID   W    G    R    AB   H    1B   2B  3B   HR  ...  HBP  BBHBP  SF  Outs  \
0   1  60  162  558  5336 NaN   891  247  31  111  ...    0    460   0  4056
1   3  86  161  677  5620 NaN  1147  216  46   83  ...    0    531   0  4128
2   5  79  162  679  5550 NaN  1088  262  63   83  ...    0    543   0  4054
3   7  96  162  780  5536 NaN   990  265  40  163  ...    0    561   0  4078
4   9  96  162  688  5441 NaN   905  247  21  181  ...   55    597  35  4087

   Outsinplay   RA        BA       OBA       SLG       OPS
0        3216  740  0.239880  0.300207  0.360195  0.660402
1        3376  643  0.265480  0.328890  0.364591  0.693480
2        3175  710  0.269550  0.334646  0.384324  0.718971
3        3145  682  0.263367  0.331146  0.414017  0.745164
4        2703  548  0.248851  0.321258  0.401764  0.723022

[5 rows x 24 columns]
ID            0
W             0
G             0
R             0
AB            0
H             0
1B            0
2B            0
3B            0
HR            0
BB            0
SO            0
SB            0
CS            0
HBP           0
BBHBP         0
SF            0
Outs          0
Outsinplay    0
RA            0
BA            0
OBA           0
SLG           0
OPS           0
dtype: int64
   ID   W    G    R    AB       H    1B   2B  3B   HR  ...  HBP  BBHBP  SF  \
0   1  60  162  558  5336  1409.0   891  247  31  111  ...    0    460   0
1   3  86  161  677  5620  1409.0  1147  216  46   83  ...    0    531   0
2   5  79  162  679  5550  1409.0  1088  262  63   83  ...    0    543   0
3   7  96  162  780  5536  1409.0   990  265  40  163  ...    0    561   0
4   9  96  162  688  5441  1409.0   905  247  21  181  ...   55    597  35

   Outs  Outsinplay   RA        BA       OBA       SLG       OPS
0  4056        3216  740  0.239880  0.300207  0.360195  0.660402
1  4128        3376  643  0.265480  0.328890  0.364591  0.693480
2  4054        3175  710  0.269550  0.334646  0.384324  0.718971
3  4078        3145  682  0.263367  0.331146  0.414017  0.745164
4  4087        2703  548  0.248851  0.321258  0.401764  0.723022

[5 rows x 24 columns]

In [121]:
df

,ID,W,G,R,AB,H,1B,2B,3B,HR,...,HBP,BBHBP,SF,Outs,Outsinplay,RA,BA,OBA,SLG,OPS
0,1,60,162,558,5336,1409.0,891,247,31,111,...,0,460,0,4056,3216,740,0.239880,0.300207,0.360195,0.660402
1,3,86,161,677,5620,1409.0,1147,216,46,83,...,0,531,0,4128,3376,643,0.265480,0.328890,0.364591,0.693480
2,5,79,162,679,5550,1409.0,1088,262,63,83,...,0,543,0,4054,3175,710,0.269550,0.334646,0.384324,0.718971
3,7,96,162,780,5536,1409.0,990,265,40,163,...,0,561,0,4078,3145,682,0.263367,0.331146,0.414017,0.745164
4,9,96,162,688,5441,1409.0,905,247,21,181,...,55,597,35,4087,2703,548,0.248851,0.321258,0.401764,0.723022
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
576,1153,71,162,680,5592,1429.0,1037,205,29,158,...,0,471,0,4163,3370,826,0.255544,0.313376,0.387339,0.700715
577,1155,76,162,750,5518,1380.0,871,287,28,194,...,81,680,25,4138,2803,907,0.250091,0.331030,0.417724,0.748754
578,1157,83,162,836,5568,1526.0,1037,288,39,162,...,75,551,57,4042,3116,867,0.274066,0.336302,0.427083,0.763385
579,1159,67,162,758,5517,1507.0,1028,278,59,142,...,0,388,0,4010,3066,967,0.273156,0.320914,0.422150,0.743064
580,1161,67,162,667,5491,1353.0,850,311,27,165,...,64,516,49,4138,3145,773,0.246403,0.308620,0.403023,0.711643

In [122]:
df.skew()

ID            0.000000
W            -0.336706
G            -3.938677
R            -0.278472
AB           -3.717478
H            -1.769487
1B           -1.271870
2B           -0.337987
3B            0.565988
HR            0.162969
BB           -0.073423
SO           -0.107940
SB            0.940786
CS            0.798992
HBP           0.737297
BBHBP        -0.091898
SF            0.606925
Outs         -3.777291
Outsinplay   -1.751798
RA           -0.126519
BA            0.097836
OBA           0.144050
SLG           0.171802
OPS           0.199700
dtype: float64

In [123]:
df['R']=np.log1p(df['R'])
df['R'].skew()
df.skew()

ID            0.000000
W            -0.336706
G            -3.938677
R            -0.983357
AB           -3.717478
H            -1.769487
1B           -1.271870
2B           -0.337987
3B            0.565988
HR            0.162969
BB           -0.073423
SO           -0.107940
SB            0.940786
CS            0.798992
HBP           0.737297
BBHBP        -0.091898
SF            0.606925
Outs         -3.777291
Outsinplay   -1.751798
RA           -0.126519
BA            0.097836
OBA           0.144050
SLG           0.171802
OPS           0.199700
dtype: float64